name: Build

on:
  push

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install npm-run-all
        run: npm install npm-run-all

      - name: Check formatting
        run: npm run build

