name: Pages deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
 
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          BASE_PATH: /${{ github.event.repository.name }}

      - name: Upload artifacts to github pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy pages
        uses: actions/deploy-pages@v4

